ITS-HCD/nysds

packages/nys-textarea/src/nys-textarea.mdx, packages/nys-textarea/src/nys-textarea.ts, packages/nys-textinput/src/nys-textinput.ts
Implement elementInternal on `nys-textarea` to replace the old form controller branch code. The purpose of this is to allow custom components to interact with native form and submissions' 
_For complex or multi-part PRs, list significant changes made:_
- **Modified components**: textarea implements elementInternal
Tested on:
=> Feature: form textarea internal

packages/nys-select/src/nys-select.ts
Implement elementInternal on `nys-select` to replace the old form controller branch code. The purpose of this is to allow custom components to interact with native form and submissions' 
_For complex or multi-part PRs, list significant changes made:_
- **Modified components**: select implements elementInternal
Tested on:
=> Feature: form select internal

package-lock.json, packages/nys-radiobutton/src/nys-radiobutton.mdx, packages/nys-radiobutton/src/nys-radiobutton.stories.ts, packages/nys-radiobutton/src/nys-radiobutton.ts, packages/nys-radiobutton/src/nys-radiogroup.ts
Implement elementInternal on `nys-radiogroup` and `nys-radiobutton` to replace the old form controller branch code. The purpose of this is to allow custom components to interact with native form and submissions' 
- **Modified components**: `nys-radiogroup` and `nys-radiobutton` implements elementInternal
Tested on:
=> Feature: form radio internal

package-lock.json, packages/nys-globalfooter/src/nys-globalfooter.mdx, packages/nys-globalfooter/src/nys-globalfooter.stories.ts, packages/nys-globalfooter/src/nys-globalfooter.ts, packages/nys-globalheader/src/nys-globalheader.stories.ts, packages/nys-globalheader/src/nys-globalheader.ts, packages/nys-textinput/src/nys-textinput.ts
Removed default linking from [window.location.origin](https://developer.mozilla.org/en-US/docs/Web/API/Location/origin) to no link on the global footer's agency name.
Revise global header storybook
=> Fix: globalfooter/header link

packages/nys-button/src/nys-button.ts, packages/nys-checkbox/src/nys-checkbox.ts, packages/nys-checkbox/src/nys-checkboxgroup.ts, packages/nys-icon/src/nys-icon.ts, packages/nys-radiobutton/src/nys-radiobutton.ts, packages/nys-radiobutton/src/nys-radiogroup.ts, packages/nys-select/src/nys-select.ts, packages/nys-textarea/src/nys-textarea.ts, packages/nys-textinput/src/nys-textinput.ts, packages/nys-toggle/src/nys-toggle.ts
Reflect "name" prop on components and fix showError issue on `nys-radiogroup`
This is to solve the issue of React demo not submitting the form.
I remember Jesse in the prev weeks had pointed out what to reflect or not, so my question is should the "name" prop be reflected (even though it fixes the React form submission issue)?
https://lit.dev/docs/components/properties/#reflected-attributes
=> Reflect "name" prop and fix showErrrrorr on radiogroup

packages/nys-checkbox/src/nys-checkbox.stories.ts, packages/nys-checkbox/src/nys-checkbox.ts, packages/nys-radiobutton/src/nys-radiobutton.stories.ts, packages/nys-radiobutton/src/nys-radiobutton.ts
make sure slot is explicitly defined to `name="description`
=> Fix: nys-radiobutton and nys-checkbox slotted description

packages/nys-textinput/src/nys-textinput.styles.ts, packages/nys-textinput/src/nys-textinput.ts
Added a "password eye" icon to the TextInput component to allow users to toggle password visibility.
=> Add password eye toggle

packages/styles/src/nysds.css
Make components invisible while JS loads to avoid flashing unstyled components on screen
=> make undefined components invisible

vite.config.js
The bundle issue caused the first known problem in Dan's React demo.
Based on Eric's insight, I can confirm that taking out the `id.startWith("@nysds/")` in the main `vite.config.js` fixes the React problem as it removes the extra imports.
https://github.com/ITS-HCD/nysds/issues/448 🎟️
BEFORE:
AFTER:
=> Took out `id.startWith("@nysds/")` from vite.config.js

packages/nys-button/src/nys-button.mdx, packages/nys-button/src/nys-button.stories.ts, packages/nys-button/src/nys-button.ts
Add `target` prop to allow devs to customize the url target. default is "_self"
=> allow dev to customize target type of button when passing a URL

packages/nys-radiobutton/src/nys-radiobutton.styles.ts
Issue flagged about how text was not centered properly relative to the radio button. Issue was caused by margin bleeding into the custom radio button styles that was set in the user agent stylesheet. By changing `margin-bottom: auto` to `margin: 0 0 auto 0` though almost the same thing, properly overrides the stylesheet and fixes the misalignment. 
before: 
after:
=> Fix: Radiobutton Text Alignment

packages/nys-alert/src/nys-alert.stories.ts, packages/nys-alert/src/nys-alert.styles.ts, packages/nys-alert/src/nys-alert.ts, packages/nys-button/src/nys-button.ts, packages/nys-unavheader/src/nys-unavheader.ts
Fix issue where `<nys-button>` inside other components are not interactable with the keyboard. The button itself can be clicked, but the "enter" or "space" key but does not register in unavheader and alert
Closes #510
=> Hotfix: Button subcomponent not clickable via keyboard

packages/nys-skipnav/src/nys-skipnav.styles.ts
Design noticed border radius in not rounded by 2px and I fixed an issue with transition slighting not left align.
This is **not** a breaking change. 
- `nys-skipnav`
=> Fix: skipnav radius and left transition out of bound

packages/styles/src/core/tokens.css
Update the semantic color variable from old "neutral" to "base". Not deleting `--nys-color-neutral-#`.
```
--nys-color-neutral
--nys-color-neutral-weak
TO
--nys-color-base
--nys-color-base-weak
```
Ticket https://github.com/ITS-HCD/nysds-site/issues/174 🎟️ is reliant on this change.
=> Enhancement: new tokens colors

packages/styles/src/core/tokens.css, src/stories/Design-Tokens.mdx
Add missing color tokens and ramps from Figma foundation file and add missing `--nys-color-text-weakest` to token.css
This PR closes #614  🎟️ (reconcile missing tokens from Figma)
This PR closes #615  🎟️ (add missing token text-weakest)
- **Documentation updates**: storybook tokens page
=> Documentation: tokens additions to storybook

packages/nys-alert/src/nys-alert.mdx, packages/nys-button/src/nys-button.mdx, packages/nys-button/src/nys-button.ts, packages/nys-checkbox/src/nys-checkbox.mdx, packages/nys-checkbox/src/nys-checkbox.ts, packages/nys-checkbox/src/nys-checkboxgroup.ts, packages/nys-radiobutton/src/nys-radiobutton.mdx, packages/nys-radiobutton/src/nys-radiobutton.ts, packages/nys-radiobutton/src/nys-radiogroup.ts, packages/nys-select/src/nys-select.mdx, packages/nys-select/src/nys-select.stories.ts, packages/nys-select/src/nys-select.ts, packages/nys-skipnav/src/nys-skipnav.ts, packages/nys-textarea/src/nys-textarea.mdx, packages/nys-textarea/src/nys-textarea.ts, packages/nys-textinput/src/nys-textinput.mdx, packages/nys-textinput/src/nys-textinput.ts, packages/nys-toggle/src/nys-toggle.mdx, packages/nys-toggle/src/nys-toggle.ts, templates/mdx.template.hbs
Fix storybook events documentation, code revision for dispatch events switch to have prefix `nys-` and fix issue with checkbox keydown validation.
- PR Closes #623 
- PR Closes #617 
- **Modified components**: mainly `nys-checkbox` validation bug + event update on most components
- **Documentation updates**: Storybook's event section
Tested on [React Demo](https://github.com/ITS-HCD/nysds-react-demo) repo.
=> Fix: event documentation & bugs

packages/nys-select/src/nys-select.stories.ts
Select story uses nys-icon and needed to have that added as an import so the carat shows up
=> Fix select story, properly loads nys-icon

packages/nys-icon/src/nys-icon.mdx, packages/nys-icon/src/nys-icon.stories.ts, packages/nys-icon/src/nys-icon.test.ts, packages/nys-icon/src/nys-icon.ts
Renaming `label` to `ariaLabel` and removing `ariaDescription` prop on `nys-icon`
Closes #735 🎟️
=> Fix: icon prop update

packages/nys-icon/src/nys-icon.figma.ts, packages/nys-tooltip/src/nys-tooltip.ts
Attempted fix at a problem with the reference site.
Problem with reference site not having focusable for `nys-tooltip`. I suspect this is due to client-side rendering for Storybook and React (which is why it works) versus 11.ty(how HTML is static and render first)
=> Fix: tooltip rendering

packages/nys-fileinput/src/nys-fileitem.styles.ts
Fixes the fileinput item being transparent...
Cloese #752 🎟️
=> Fix transparent background to not be

packages/nys-textarea/src/nys-textarea.styles.ts
=> add font family so it isnt monospace

packages/nys-avatar/src/nys-avatar.figma.ts, packages/nys-avatar/src/nys-avatar.mdx, packages/nys-avatar/src/nys-avatar.stories.ts, packages/nys-avatar/src/nys-avatar.styles.ts, packages/nys-avatar/src/nys-avatar.test.ts, packages/nys-avatar/src/nys-avatar.ts
New updates to `nys-avatar`:
- new base color
- removed `shape` prop
- new logic that changes the inner foreground initial/icon color based on the `color` prop
- Add `disabled` prop
- Add `interactive` prop
:warning: This is **100%** a breaking change upstream! :warning:
@esteinborn Please announce the removal of the `shape` property, as design dictates that the avatar should have only a "circle" shape. This is a **breaking change to EVERYONE** using this component!
Closes #346 🎟️
=> Enhancement: `nys-avatar`

packages/nys-globalheader/src/nys-globalheader.ts
`nys-globalheader` should keep an active state for sub-page links like:
foundations -> foundations/accessibility -> foundations/accessibility/digital-experiences/
Closes #838 🎟️
=> Fix: Active link on `nys-globalheader` for sub links

packages/nys-checkbox/src/nys-checkboxgroup.ts, packages/nys-radiobutton/src/nys-radiogroup.ts
Attempt to fix an issue in the `nys-radiogroup` component where the `setValidity` call on `ElementInternals` was failing when the first child radio input element was not yet available. The error occurred when the component tried to validate the required state immediately on initialization.  
Closes #883 🎟️
=> Fix: validity issue

package-lock.json, packages/nys-checkbox/src/nys-checkbox.mdx, packages/nys-checkbox/src/nys-checkbox.stories.ts, packages/nys-checkbox/src/nys-checkboxgroup.ts, packages/nys-fileinput/src/nys-fileinput.mdx, packages/nys-fileinput/src/nys-fileinput.stories.ts, packages/nys-fileinput/src/nys-fileinput.ts, packages/nys-label/package.json, packages/nys-label/src/nys-label.mdx, packages/nys-label/src/nys-label.stories.ts, packages/nys-label/src/nys-label.styles.ts, packages/nys-label/src/nys-label.ts, packages/nys-radiobutton/src/nys-radiobutton.mdx, packages/nys-radiobutton/src/nys-radiobutton.stories.ts, packages/nys-radiobutton/src/nys-radiogroup.ts, packages/nys-select/src/nys-select.mdx, packages/nys-select/src/nys-select.stories.ts, packages/nys-select/src/nys-select.ts, packages/nys-textarea/src/nys-textarea.mdx, packages/nys-textarea/src/nys-textarea.stories.ts, packages/nys-textarea/src/nys-textarea.ts, packages/nys-textinput/src/nys-textinput.mdx, packages/nys-textinput/src/nys-textinput.stories.ts, packages/nys-textinput/src/nys-textinput.ts, packages/nys-tooltip/src/nys-tooltip.mdx, packages/nys-tooltip/src/nys-tooltip.ts
Add the `tooltip` prop to all form-related components. Additional cleanup on `nys-label` and storybook heading revisions.
Closes #734 🎟️
=> Feature: tooltip prop

packages/nys-select/src/nys-select.ts
NYS prefix for `nys-change` event is missing on `nys-select` component.
=> BUG: Add missing nys-prefix for `nys-select`

packages/nys-fileinput/src/nys-fileinput.ts
Fix the issue when `required` is set on `nys-fileinput`, it wasn't getting validated by the form submission. 
Closes #916 🎟️
=> Fix: `nys-fileinput` validation

packages/nys-checkbox/src/nys-checkbox.ts
Addresses a fix for the build test fail on `nys-checkbox` and fixes the text clicking not toggling the status of the checkbox
_Indicate if this update is a breaking change with **one** of the following statements:_
Closes #930 🎟️
=> Fix: `nys-checkbox` A11y test fail & labels not toggling checkbox

packages/nys-checkbox/src/nys-checkbox.mdx, packages/nys-checkbox/src/nys-checkbox.stories.ts, packages/nys-checkbox/src/nys-checkbox.ts, packages/nys-checkbox/src/nys-checkboxgroup.ts, packages/nys-divider/src/nys-divider.mdx, packages/nys-fileinput/src/nys-fileinput.mdx, packages/nys-fileinput/src/nys-fileinput.stories.ts, packages/nys-fileinput/src/nys-fileinput.ts, packages/nys-label/src/nys-label.stories.ts, packages/nys-label/src/nys-label.styles.ts, packages/nys-label/src/nys-label.ts, packages/nys-modal/src/nys-modal.mdx, packages/nys-modal/src/nys-modal.stories.ts, packages/nys-radiobutton/src/nys-radiobutton.mdx, packages/nys-radiobutton/src/nys-radiobutton.stories.ts, packages/nys-radiobutton/src/nys-radiobutton.ts, packages/nys-radiobutton/src/nys-radiogroup.ts, packages/nys-select/src/nys-select.mdx, packages/nys-select/src/nys-select.stories.ts, packages/nys-select/src/nys-select.ts, packages/nys-textarea/src/nys-textarea.mdx, packages/nys-textarea/src/nys-textarea.stories.ts, packages/nys-textarea/src/nys-textarea.ts, packages/nys-textinput/src/nys-textinput.mdx, packages/nys-textinput/src/nys-textinput.stories.ts, packages/nys-textinput/src/nys-textinput.ts, packages/nys-toggle/src/nys-toggle.mdx, packages/nys-toggle/src/nys-toggle.stories.ts, packages/nys-toggle/src/nys-toggle.styles.ts, packages/nys-toggle/src/nys-toggle.ts
Add `invert` prop to form-related components. 
**Note**: some form-related components will not need this, like nys-button, due to how they are surrounded by a container with color already.
⚠️ _May need to change nys-tooltip prop inverted to be invert (for another PR)_
⚠️ _May need designers to take on how each component looks on dark backgrounds...this PR solves the text on dark background issue by inverting it (for another PR)_
Closes #879 🎟️
=> Enhancement: invert prop
