ITS-HCD/nysds

packages/nys-globalheader/src/nys-globalheader.mdx
packages/nys-globalheader/src/nys-globalheader.styles.ts
packages/nys-globalheader/src/nys-globalheader.ts

Minor change to a style variable name for consistent ordering and removed default linking for global Logo
https://github.com/ITS-HCD/nysds/issues/288 🎟️
https://github.com/ITS-HCD/nysds/issues/327 🎟️

Fix: globalheader bugs

---

packages/nys-checkbox/src/nys-checkbox.mdx
packages/nys-checkbox/src/nys-checkbox.stories.ts
packages/nys-checkbox/src/nys-checkbox.ts
packages/nys-checkbox/src/nys-checkboxgroup.ts

Implement elementInternal on `nys-checkboxgroup` and `nys-checkbox` to replace the old form controller branch code. The purpose of this is to allow custom components to interact with native form and submissions' 
_For complex or multi-part PRs, list significant changes made:_
- **Modified components**: `nys-checkboxgroup` and `nys-checkbox` implements elementInternal
Tested on:

Feature: form checkbox internal

---

packages/nys-button/src/nys-button.mdx
packages/nys-button/src/nys-button.stories.ts
packages/nys-button/src/nys-button.ts
packages/nys-select/src/nys-select.ts
packages/nys-textarea/src/nys-textarea.ts
packages/nys-textinput/src/nys-textinput.ts

Implement elementInternal on `nys-button` to replace the old form controller branch code. The purpose of this is to allow custom components to interact with native form and submissions' 
- **Modified components**: `nys-button` implements elementInternal
Tested on:

Feature: form button internal

---

packages/nys-alert/src/nys-alert.ts
packages/nys-avatar/src/nys-avatar.ts
packages/nys-button/src/nys-button.ts
packages/nys-checkbox/src/nys-checkbox.ts
packages/nys-checkbox/src/nys-checkboxgroup.ts
packages/nys-globalfooter/src/nys-globalfooter.ts
packages/nys-globalheader/src/nys-globalheader.ts
packages/nys-icon/src/nys-icon.ts
packages/nys-radiobutton/src/nys-radiobutton.ts
packages/nys-radiobutton/src/nys-radiogroup.ts
packages/nys-select/src/nys-option.ts
packages/nys-select/src/nys-select.ts
packages/nys-textarea/src/nys-textarea.ts
packages/nys-textinput/src/nys-textinput.ts
packages/nys-toggle/src/nys-toggle.ts
packages/nys-unavheader/src/nys-unavheader.ts

add `reflect:true` to all properties to mimic native components

Fix: reflect properties

---

packages/nys-unavheader/src/nys-unavheader.styles.ts

Remove the `width: 100%` that caused scrolling on smaller screens

Fix: UNAV scroll issue

---

packages/nys-checkbox/src/nys-checkbox.ts

Fix issue with single checkbox validation not appearing right.

Fix checkbox validation not working properly

---

packages/nys-radiobutton/src/nys-radiogroup.ts
packages/nys-select/src/nys-select.ts
packages/nys-textarea/src/nys-textarea.ts
packages/nys-textinput/src/nys-textinput.ts

Fix issue with showError showing at initial load
None

Fix issue with showError

---

packages/nys-unavheader/src/nys-unavheader.styles.ts

Reduced height of the logo to Size 500 (40px).
Adjusted spacing above and below logo (padding) from 2px to 8px.
_Indicate if this update is a breaking change with **one** of the following statements:_

Fix: size of logo, spacing above and below logo

---

packages/nys-alert/src/nys-alert.styles.ts
packages/nys-checkbox/src/index.ts
packages/nys-checkbox/src/nys-checkbox.stories.ts
packages/nys-checkbox/src/nys-checkbox.styles.ts
packages/nys-checkbox/src/nys-checkbox.ts
packages/nys-checkbox/src/nys-checkboxgroup.ts
packages/nys-radiobutton/src/index.ts
packages/nys-radiobutton/src/nys-radiogroup.ts
packages/nys-select/src/index.ts
packages/nys-textinput/src/nys-textinput.ts

Import checkbox/radio grouping and revisited these components to fix the way they bubble up details to formData.
Not a breaking change
- Select's option import
- Checkbox's group import
- Radiobutton's group import
- Logic changes in radiogroup and checkbox/group
- Alert's text-align
Done in https://github.com/ITS-HCD/nysds-react-demo

Fix: Form react issues (part 2)

---

packages/nys-checkbox/src/nys-checkbox.styles.ts
packages/nys-radiobutton/src/nys-radiobutton.styles.ts
packages/nys-select/src/nys-select.styles.ts
packages/nys-textarea/src/nys-textarea.styles.ts
packages/nys-textinput/src/nys-textinput.styles.ts

Apply :host Font size to the actual HTML elements within a component (nys-select is already being applied it seems)
Ticket https://github.com/ITS-HCD/nysds/issues/381 🎟️

Apply size to textinput and textarea

---

packages/styles/src/core/reset.css
packages/styles/src/nysds.css

Add CSS Reset to nysds.css
_Closes #361_
n/a

Add CSS Reset to nysds.css

---

package-lock.json

update package-lock.json for updated Vite install

Update vite dependency

---

package-lock.json

Package.lock.json updates:

---

packages/nys-alert/src/nys-alert.styles.ts
packages/nys-alert/src/nys-alert.ts
packages/nys-avatar/src/nys-avatar.stories.ts
packages/nys-avatar/src/nys-avatar.ts
packages/nys-checkbox/src/nys-checkbox.styles.ts
packages/nys-checkbox/src/nys-checkbox.ts
packages/nys-errormessage/src/nys-errormessage.ts
packages/nys-select/src/nys-select.ts
packages/nys-toggle/src/nys-toggle.styles.ts
packages/nys-toggle/src/nys-toggle.ts

Icons are resized after boundary boxes are applied. This PR fixes some of the components impacted by this change.
https://github.com/ITS-HCD/nysds/issues/430 🎟️
Components impacted by icon change:

Fix: icons resize within components

---

package.json
packages/styles/package.json
packages/styles/src/nysds.css
vite.config.js

specifically define all NYS elements in :not(:defined) format to hide on page load until initialized

Styles should hide all unfdefined elements

---

packages/nys-alert/src/nys-alert.ts
packages/nys-globalfooter/src/nys-globalfooter.ts
packages/nys-globalheader/src/nys-globalheader.ts
packages/nys-textarea/src/nys-textarea.ts
packages/nys-textinput/src/nys-textinput.ts

Resolved console warnings related to Lit's "scheduled an update" by using async/await on certain functions within component lifecycle methods.
https://github.com/ITS-HCD/nysds/issues/468 🎟️

Fix issue with lit warning "scheduled an update"

---

packages/styles/src/core/reset.css
packages/styles/src/core/tokens.css
packages/styles/src/core/typography.css

Apply the change to files tokens.css and reset.css for headings variables
https://github.com/ITS-HCD/nysds/issues/471 🎟️

Update token and reset for headings

---

packages/styles/src/core/reset.css
packages/styles/src/core/tokens.css
packages/styles/src/core/typography.css

Revert "Update token and reset for headings"

---

.storybook/main.ts
.storybook/preview-head.html
package-lock.json
package.json
packages/nys-alert/package.json
packages/nys-avatar/package.json
packages/nys-button/package.json
packages/nys-checkbox/package.json
packages/nys-errormessage/package.json
packages/nys-errormessage/src/nys-errormessage.mdx
packages/nys-globalfooter/package.json
packages/nys-globalheader/package.json
packages/nys-globalheader/src/nys-globalheader.mdx
packages/nys-icon/package.json
packages/nys-label/package.json
packages/nys-label/src/nys-label.mdx
packages/nys-radiobutton/package.json
packages/nys-select/package.json
packages/nys-select/src/nys-select.mdx
packages/nys-textarea/package.json
packages/nys-textinput/package.json
packages/nys-toggle/package.json
packages/nys-unavfooter/package.json
packages/nys-unavheader/package.json
packages/styles/package.json
packages/styles/src/nysds.css
plopfile.js
src/stories/Typography.mdx
vite.config.js
vite.config.umd.js

Release/prep 1.1.7

---

package-lock.json
package.json
packages/nys-alert/package.json
packages/nys-avatar/package.json
packages/nys-button/package.json
packages/nys-checkbox/package.json
packages/nys-errormessage/package.json
packages/nys-globalfooter/package.json
packages/nys-globalheader/package.json
packages/nys-icon/package.json
packages/nys-label/package.json
packages/nys-radiobutton/package.json
packages/nys-select/package.json
packages/nys-skipnav/package.json
packages/nys-skipnav/vite.config.js
packages/nys-textarea/package.json
packages/nys-textinput/package.json
packages/nys-toggle/package.json
packages/nys-unavfooter/package.json
packages/nys-unavheader/package.json
packages/styles/package.json
packages/styles/src/nysds.css
plopfile.js
templates/package.template.hbs
templates/viteconfig.template.hbs
vite.config.js
vite.config.umd.js

★ NYSDS v.1.1.8
- A visible skip link for keyboard and screen reader users to jump directly to the main content.
_Created by Robert Chen ([@NovaCat35](https://github.com/NovaCat35))_
_Created by Robert Chen ([@NovaCat35](https://github.com/NovaCat35))_
- Radiobutton not rendering first radio if entered in dynamically in Angular
- #505
- Better align icon and text in `nys-alert`
- #508
- Button subcomponent not clickable via keyboard
- #510
- No breaking changes
_Fixed by Robert Chen ([@NovaCat35](https://github.com/NovaCat35)), and Emily Gorelik ([@emilygorelik](https://github.com/emilygorelik))_
- Eye Toggle of Password field is not keyboard focusable
- #519
- If you notice any issues, please add them to [our GitHub Issue Tracker](https://github.com/ITS-HCD/nysds/issues)
**Full …

Prep for 1.1.8 release

---

packages/nys-alert/src/nys-alert.test.ts

Create testing (wtr) for `nys-alert` component
Ticket https://github.com/ITS-HCD/nysds-site/issues/154 🎟️

WTR: alert test

---

packages/nys-globalheader/src/nys-globalheader.test.ts
packages/nys-globalheader/src/nys-globalheader.ts

Create testing (wtr) for `nys-globalheader` component
Ticket https://github.com/ITS-HCD/nysds-site/issues/154 🎟️

WTR: globalheader test

---

.github/workflows/test-node-js.yaml

remove second round of building since it gets built by the test

remove extra redundant test

---

.github/workflows/test-node-js.yaml
.storybook/main.ts
package-lock.json
package.json
packages/nys-alert/package.json
packages/nys-avatar/package.json
packages/nys-backtotop/package.json
packages/nys-button/package.json
packages/nys-checkbox/package.json
packages/nys-errormessage/package.json
packages/nys-fileinput/package.json
packages/nys-fileinput/src/nys-fileitem.styles.ts
packages/nys-globalfooter/package.json
packages/nys-globalheader/package.json
packages/nys-icon/package.json
packages/nys-label/package.json
packages/nys-radiobutton/package.json
packages/nys-select/package.json
packages/nys-skipnav/package.json
packages/nys-textarea/package.json
packages/nys-textinput/package.json
packages/nys-toggle/package.json
packages/nys-unavfooter/package.json
packages/nys-unavheader/package.json
packages/styles/package.json
packages/styles/src/nysds.css
plopfile.js
vite.config.js
vite.config.umd.js

Prep for 1.4.0

---

packages/nys-tooltip/src/nys-tooltip.ts

_Provide a brief summary of the changes that we can use in the changelog._
_Indicate if this update is a breaking change with **one** of the following statements:_
:warning: This is **potentially** a breaking change.  
:warning: This is a **breaking change**.
_Closes #_[issue_no]\_
_If this PR depends on other PRs (e.g., documentation changes in another repo), list them here._
_Provide a link to a demo or deployment preview, if available._
_Provide a clear and concise summary of the problem this PR solves._
_Provide a summary of the solution this PR offers._
_For complex or multi-part PRs, list significant changes made:_
- **New components**: (e.g., `Modal` component)
- **Modified components**: (e.g., updates to `Button` component for new styling)
- …

Update aria function on tooltip

---

package-lock.json
package.json
packages/nys-alert/package.json
packages/nys-avatar/package.json
packages/nys-backtotop/package.json
packages/nys-button/package.json
packages/nys-checkbox/package.json
packages/nys-errormessage/package.json
packages/nys-fileinput/package.json
packages/nys-globalfooter/package.json
packages/nys-globalheader/package.json
packages/nys-icon/package.json
packages/nys-label/package.json
packages/nys-radiobutton/package.json
packages/nys-select/package.json
packages/nys-skipnav/package.json
packages/nys-textarea/package.json
packages/nys-textinput/package.json
packages/nys-toggle/package.json
packages/nys-tooltip/package.json
packages/nys-unavfooter/package.json
packages/nys-unavheader/package.json
packages/styles/package.json
packages/styles/src/nysds.css
plopfile.js
vite.config.js
vite.config.umd.js

Release/prep 1.5.0

---

packages/nys-textinput/src/nys-textinput.styles.ts

fix overflow where if width is set to size thats larger than parent container it would overflow

Text Input: fix overflowing container bug

---

packages/nys-checkbox/src/nys-checkbox.styles.ts

Add missing hover and pressed states to checked checkbox 
https://github.com/user-attachments/assets/79a183ad-6c81-4497-95a1-290023bf3a64

Enhancement: Checkbox - Checked hover states

---

packages/nys-button/src/nys-button.test.ts

Removed form submission testing from `<nys-button>` (all multiple attempts have failed, I have to resort to pulling the plug on internal form test). Updated tests now test that the native <button> type attribute is set correctly for all button types, and fixed issues with event dispatching in the component.
Closes #862 🎟️

Fix: test build

---

packages/nys-accordion/package.json
packages/nys-alert/package.json
packages/nys-avatar/package.json
packages/nys-backtotop/package.json
packages/nys-badge/package.json
packages/nys-button/package.json
packages/nys-checkbox/package.json
packages/nys-divider/package.json
packages/nys-errormessage/package.json
packages/nys-fileinput/package.json
packages/nys-globalfooter/package.json
packages/nys-globalheader/package.json
packages/nys-icon/package.json
packages/nys-label/package.json
packages/nys-radiobutton/package.json
packages/nys-select/package.json
packages/nys-skipnav/package.json
packages/nys-stepper/package.json
packages/nys-textarea/package.json
packages/nys-textinput/package.json
packages/nys-toggle/package.json
packages/nys-tooltip/package.json
packages/nys-unavfooter/package.json
packages/nys-unavheader/package.json
templates/package.template.hbs

Add checking script on individual components so we can more easily target fixes

Enhance: lit analyze checker

---

packages/nys-badge/src/nys-badge.figma.ts

Revert "dont show prefix if toggled off"

---

packages/nys-label/src/nys-label.styles.ts

Fix: Label Flag Wraps Properly

---

packages/nys-pagination/src/nys-pagination.ts
packages/nys-unavheader/src/nys-unavheader.test.ts

Fix the a11y issue with checkbox label and a separate issue with unavheader

Fix checkbox labels failing test

---

package-lock.json
packages/nys-checkbox/src/nys-checkbox.ts

tar-fs": {
"version": "3.1.1",
}

Update tar-fs package
